---
- name: Pull Docker Image
  hosts: all
  tasks:
    - name: Pull taskmanager_angular image
      docker_image:
        name: neha89358/taskmanager_angular
        source: pull
    - name: Pull taskmanager_express image
      docker_image:
        name: neha89358/taskmanager_express
        source: pull
